{
 "title": "Dashboard final posta",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Artillery", "query": "artillery-node" },
   {
    "name": "Container",
    "query": "arqsoft-2c2020-tp1_node_1,arqsoft-2c2020-tp1_node_2,arqsoft-2c2020-tp1_node_3,arqsoft-2c2020-tp1_gunicorn_1,arqsoft-2c2020-tp1_nginx_1"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.rps.mean)"
    }
   ]
  },
  {
   "title": "Scenarios launched",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.scenariosCreated)"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.scenarioDuration.median)"
    },
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.scenarioDuration.max)"
    },
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.scenarioDuration.min)"
    }
   ]
  },
  {
   "title": "Completed vs pending (stacked)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.requestsCompleted)"
    },
    {
     "target": "aliasByMetric(stats.gauges.$Artillery.pendingRequests)"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.errors.*)"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Success')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.504, 'Timeout')"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Core Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(derivative(stats.gauges.cadvisor.$Container.cpu_cumulative_usage), 10000000000), 'CPU')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "alias(scale(stats.gauges.cadvisor.$Container.memory_working_set, 9.53674316e-7), 'Memory')"
    }
   ]
  }
 ]
}